version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi.nonroot.Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/data/app
      - ./tests:/usr/data/tests
    # environment:
    #   - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    env_file:
      - app/.env
    healthcheck:
      test:
        - CMD
        - wget -S --spider http://localhost:8000/docs
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.7-alpine
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
      - './assets/postgres/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql'

  frontend:
    build:
      context: ./frontend
      dockerfile: front.Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  web:
    image: nginx:latest
    volumes:
      - ./assets/nginx/nginx.http.config:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
    -  fastapi
volumes:
  pgdata:


